feat-12: Comphrehensive naming consolidation for Base1024Emoji
DimensionDev/coda pull request #13
Opened 2020-05-29 08:15 UTC by neruthes

Close #12.

2020-05-29 10:32 UTC, septs requested changes

2020-05-29 10:32 UTC, septs commented on README.md
> +encode(decoded, Codec.Base1024Emoji);    // '🐟🔂🏁🤖💧🚊😤🀄'
keep comments, aligned

2020-05-29 10:32 UTC, septs commented on src/constants/index.ts
> +export const Base1024Emoji_alphabet = expandPoints(_Base1024Emoji_alphabet)
```suggestion
export const Base1024EmojiAlphabet = expandPoints(_Base1024EmojiAlphabet)
```

2020-05-30 10:17 UTC, Tedko reviewed
Leave these to developers

2020-05-30 10:17 UTC, neruthes commented on README.md
> +encode(decoded, Codec.Base1024Emoji);    // '🐟🔂🏁🤖💧🚊😤🀄'
Done

2020-06-01 10:44 UTC, neruthes commented
Are conflicts well resolved? 🤔

cc @septs

2020-06-01 10:50 UTC, merged